### PR TITLE
[WIP] IOUEscrow

### PR DESCRIPTION
**Pull request by dangell7**
## High Level Overview of Change

Adding functionality for IOUEscrow Amendment

### Context of Change

- [x] Transactions: Updated `Amount` - string -> Amount
- [x] Ledger Object: Updated `Amount` - string -> Amount
- [x] FundWallet: Added links to fund the IOUEscrow dev network
- [x] Test: PaymentChannel: Create, Claim, Fund - Escrow: Create

I also added an Issue Currency function on the setup client. This issues a currency for the wallet & destination.

I removed the PAYCHANNEL from the reusable and moved it into the test. (synergy)

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Before / After

XRP ONLY for Payment Channel & Escrow / IOU/XRP for Payment Channel & Escrow

## Test Plan

Please review the tests and let me know if you see more. There are much more tests in the rippled library. We can definitely adopt them.

I would like to discuss the gateway setup and having access to an issued token in each test suite.

Resources:

pip3 install git+https://github.com/Transia-RnD/xrpl.js.git@iouescrow

### CODE REVIEW

**Comment by jonathanlei** [comment]
Please merge with the latest master changes so that tests will pass (we took down the nftDevnet test since it's deprecated)

**Comment by mvadari** [comment]
There appears to be something wrong with the diff - there's a bunch of stuff from other PRs.

Also, is your pip link in the README supposed to say "xrpl.js.git"?

**Comment by dangell7** [comment]
https://github.com/XRPLF/xrpl-py/pull/514

**Comment by dangell7** [comment]
> There appears to be something wrong with the diff - there's a bunch of stuff from other PRs.
> 
> Also, is your pip link in the README supposed to say "xrpl.js.git"?

Bad rebase. tbh I'm not sure what happened. I opened another PR [here](https://github.com/XRPLF/xrpl-py/pull/514).

**Pull request closed without merging**
