### PR TITLE
Remove deprecated `full` parameter from ledger request model

### PR DESCRIPTION
**Pull request by kennyzlei**
## High Level Overview of Change

Remove deprecated full parameter from ledger request model

### Context of Change

In the [`ledger` API](https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/ledger-methods/ledger/), the `full` request parameter has been deprecated for quite awhile now.  As of Clio 2.2.0 with this particular commit https://github.com/XRPLF/clio/pull/1360, this API will return a request error if you provide that parameter.  This change removes this parameter from the ledger request model.  This change would not impact lib users as this using this parameter or setting it to true instead of default false previously would not have been used by rippled or Clio

### Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### Did you update CHANGELOG.md?

- [x] Yes
- [ ] No, this change does not impact library users

## Test Plan

Existing integration tests should continue to pass and manual testing of ledger API with xrpl-py against Clio 2.2.0 should succeed

### CODE REVIEW

**Comment by mvadari** [comment]
Please update the changelog.

**Comment by kennyzlei** [comment]
@mvadari updated the changelog!  thanks for the reminder

**Review by mvadari — APPROVED** [review]

**Review by pdp2121 — APPROVED** [review]

**Comment by kennyzlei** [comment]
@pdp2121 @mvadari thanks for the reviews/approvals!  I don't have write access to be able to merge, so please feel free to merge this PR when it is the right time 🙏

**Comment by arihantkothari** [comment]
so, does this mean everyone using xrpl-py needs to upgrade immediately ?

**Comment by angelmacm** [comment]
I'm not quite sure if this is relevant

I've manually modified the above file on my xrpl-py pip release on my device and even cloned the repository in place of the current xrpl-py release on pip. Both times I got an error that said `Request failed, notSupported: Not supported field 'accounts' error occurred.`

I modified again the above file to remove the `accounts` field and it is now working.

**Comment by kennyzlei** [comment]
> I'm not quite sure if this is relevant
> 
> I've manually modified the above file on my xrpl-py pip release on my device and even cloned the repository in place of the current xrpl-py release on pip. Both times I got an error that said `Request failed, notSupported: Not supported field 'accounts' error occurred.`
> 
> I modified again the above file to remove the `accounts` field and it is now working.

@angelmacm thanks for flagging, I think it is similar in that the `accounts` field may have been deprecated for awhile too and Clio is now enforcing it.  I'll create a PR for this update as well

**Pull request merged**
