### PR TITLE
Update Github Actions to include the coverage for diff

### PR DESCRIPTION
**Pull request by ckeshava**
## High Level Overview of Change
This PR is aimed to address concerns described in https://github.com/XRPLF/xrpl-py/issues/734

This PR seeks to integrate coverage reports into the CI/CD pipeline. 

Note: I am not entirely sure if the changes are syntactically correct. At the moment, only `main` branch is considered by the Github CI/CD pipeline.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### Did you update CHANGELOG.md?

- [ ] Yes
- [x] No, this change does not impact library users

### CODE REVIEW

**Comment by mvadari** [comment]
What's the added benefit of uploading a coverage report vs. just looking at the coverage report in CI?

**Comment by ckeshava** [comment]
There is no added benefit. Github Actions removes artifacts after 90 days. It might be useful to have snapshots of these coverage reports, for debugging purposes.

**Comment by mvadari** [comment]
The coverage is already shown in the CI output, which is easier to access than an artifact. See the "Integration Test" section here for an example (this is run on this PR): https://github.com/XRPLF/xrpl-py/actions/runs/10049744134/job/27776363430?pr=735

**Comment by ckeshava** [comment]
Okay, I missed seeing the coverage reports. This existing CI/CD pipeline seems to have most of the information that we need.

**Comment by mvadari** [comment]
@ckeshava should this PR be closed?

**Pull request closed without merging**
