### PR TITLE
Fixed the issue #276 by adding missing definitions: sfCookie and ValidatedHash

### PR DESCRIPTION
**Pull request by Rachit8484**
https://github.com/XRPLF/xrpl-py/issues/276

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Comment by mvadari** [comment]
Add `ValidatedHash` as well

**Comment by mvadari** [comment]
Add tests to make sure it's correct

**Comment by ledhed2222** [comment]
Agree with @mvadari - @Rachit8484 could you please add what she asked for?

**Comment by intelliot** [comment]
Superseded by #289

**Pull request closed without merging**
