### PR TITLE
feature `NetworkID`

### PR DESCRIPTION
**Pull request by dangell7**
## High Level Overview of Change

https://github.com/XRPLF/rippled/pull/4370

### Context of Change

Added network id to the base transaction
Added network id to the `server_info` response
Added network id to the binary codec
Added network id to autofill if custom network id was supplied to client.

### Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Test Plan

No tests were written

### CODE REVIEW

**Comment by dangell7** [comment]
Usage: https://github.com/Transia-RnD/xls-playground/blob/main/py/tests/test_xls_network_id.py

```
client.network_id = get_network_id(client)
```

**Comment by justinr1234** [comment]
@dangell7 wanted to check back on this work

**Comment by dangell7** [comment]
> @dangell7 wanted to check back on this work

The js repo wanted to handle it a bit differently, I can see if there is are any other changes they want to make to the PR and then I can attempt to do the same here.

JS PR: https://github.com/XRPLF/xrpl.js/pull/2216

**Comment by pdp2121** [comment]
> > @dangell7 wanted to check back on this work
> 
> The js repo wanted to handle it a bit differently, I can see if there is are any other changes they want to make to the PR and then I can attempt to do the same here.
> 
> JS PR: [XRPLF/xrpl.js#2216](https://github.com/XRPLF/xrpl.js/pull/2216)

Hi @dangell7, do you want to work on this PR on your own or may I just take over this as well (if so could you invite me to this repo as well?) Thank you!

**Comment by dangell7** [comment]
> > > @dangell7 wanted to check back on this work
> > 
> > 
> > The js repo wanted to handle it a bit differently, I can see if there is are any other changes they want to make to the PR and then I can attempt to do the same here.
> > JS PR: [XRPLF/xrpl.js#2216](https://github.com/XRPLF/xrpl.js/pull/2216)
> 
> Hi @dangell7, do you want to work on this PR on your own or may I just take over this as well (if so could you invite me to this repo as well?) Thank you!

Added you to this repo :)

**Review by justinr1234 — APPROVED** [review]

**Review by jonathanlei — APPROVED** [review]

**Pull request merged**
