### PR TITLE
[BREAKING] fix: XRP().to_amount now expects XRP instead of drops

### PR DESCRIPTION
**Pull request by mvadari**
## High Level Overview of Change

This PR fixes a disconnect between the docs for the `XRP().to_amount` method and what the function actually did. The docs seemed to be expecting an XRP amount, but the code was expecting an amount in drops.

I think an amount in XRP makes more sense. This is technically a breaking change, but I think it's more of a bugfix.

### Context of Change

Ran into this issue while working on sidechain tooling

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

## Test Plan

CI passes.

### CODE REVIEW

**Comment by ckniffen** [comment]
I think this is a huge breaking change because anyone that relied on this will be having values orders of magnitude more.

**Comment by justinr1234** [comment]
@mvadari conflicts

**Comment by JST5000** [comment]
@mvadari why is using XRP instead of drops better here? (I know the docs say XRP, but in practice everyone using the function currently has it in drops, so should we just update the docs and call it good?) 

We should make a choice about this before 2.0

**Comment by intelliot** [comment]
Suggestion:
1. Leave the behavior of the existing function alone
2. Deprecate the existing function (and update the docs/comments to be accurate)
3. Add 2 new methods:
    - to_drops_amount
    - to_xrp_amount

Hopefully the names of the new methods make the behavior obvious 😀

**Comment by mvadari** [comment]
> Suggestion:
> 
> 1. Leave the behavior of the existing function alone
> 2. Deprecate the existing function (and update the docs/comments to be accurate)
> 3. Add 2 new functions:
>    
>    * to_drops_amount
>    * to_xrp_amount
> 
> Hopefully the names of the new methods make the behavior obvious 😀

The difficulty of this is that you can't use `Currency.to_amount` as easily, which is what I wanted.

**Review by JST5000 — APPROVED** [review]
LGTM

**Review by ckniffen — APPROVED** [review]

**Pull request merged**
