### PR TITLE
`Require Destination Tags` code sample

### PR DESCRIPTION
**Pull request by wojake**
## High Level Overview of Change
Enables `Require Destination Tags` setting on an Account

This is work for a XRPL Bounty @ [XRPLBounties/Proposals](https://github.com/XRPLBounties/Proposals/blob/main/open_bounties/0079%20Python%20Code%20Samples%202.md) for Milestone 2

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [X] Documentation Updates
- [ ] Release

### CODE REVIEW

**Comment by ckniffen** [comment]
I think we want these on the docs site now.  @jonathanlei Is this correct?

**Comment by wojake** [comment]
I'm going to close this and transfer this to xrpl.org @JST5000

**Comment by JST5000** [comment]
> This seems to be correct, I don't know where to submit my work, it's either this repo or xrpl.org. @JST5000

Ah, sorry for the confusion. Please continue to submit this work in this repo (xrpl-py). 

When we originally created the Python Code Samples bounty we were thinking that client library samples should just be runnable with minimal tweaks, while xrpl.org samples should be more teachable. (Optimizing for showing best practices vs optimizing for helping people understand by playing with it) - Later on though, we realized that the difference between them is actually pretty minimal, and so it's better to just have them all in one spot (then link to it everywhere) so we updated the bounty description to just be "add it to xrpl-dev-portal". 

Unfortunately when did that we didn't realize that there were some snippets which were already there - so that's the source of the confusion. Sorry about that.

**Comment by JST5000** [comment]
Will review on Monday

**Review by JST5000 — APPROVED** [review]
LGTM

**Review by ckniffen — APPROVED** [review]

**Comment by JST5000** [comment]
Hey @wojake, just talked with the original author of the bounty, and realized that I was mistaken about what this bounty in particular was asking for. He said that the destination tag bounty was to add python snippets to this tutorial: https://xrpl.org/require-destination-tags.html#require-destination-tags (It's linked in the [milestone description here](https://github.com/XRPLBounties/Proposals/blob/main/open_bounties/0079%20Python%20Code%20Samples%202.md), but the description could be more clear since it's the only one if it's kind in the list). 

You can probably re-use most of this code for that, but the ask would be to have a "tab" for Python for the steps of the tutorial.  Sorry I had the wrong idea about what the bounty was for. 

I'm going to close this PR since this isn't where the code should go and I'll update the milestone description to be more clear.

**Pull request closed without merging**
